<?php

namespace pay;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-05 at 17:30:03.
 */
class GatewayTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Gateway
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Gateway;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pay\Gateway::getPayment
     * @todo   Implement testGetPayment().
     */
    public function testGetPayment()
    {
        $instance = $this->object->getPayment(array('wechat' => 'jsapi'));
        $this->assertInstanceOf('pay\gateway\GatewayInterface', $instance);
    }

}
