<?php

namespace pay;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-05 at 17:29:55.
 */
class PayTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Pay
     */
    protected $object;

    /**
     * @dataProvider getPayment
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $instance     = Gateway::getPayment(['wechat' => 'native']);
        $this->object = new Pay($instance);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pay\Pay::createOrder
     * @todo   Implement testCreateOrder().
     */
    public function testCreateOrder()
    {
        //扫码支付
        $data   = array(
            'product_id'       => '123',
            'body'             => '测试交易',
            'out_trade_no'     => date('Ymd') . mt_rand(10000, 99999),
            'total_fee'        => 520,
            'spbill_create_ip' => '112.95.195.168',
            'openid'           => 'oK14vt-2cevUlgcPvuzZJOZqp7_k'
        );
        $this->object->instance->setMode(2);
        $result = $this->object->createOrder($data);
        $this->assertNotFalse($result);
    }

    /**
     * @covers pay\Pay::notify
     * @todo   Implement testNotify().
     */
    public function testNotify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\Pay::verify
     * @todo   Implement testVerify().
     */
    public function testVerify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
