<?php

namespace pay\gateway\wechat\lib;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-05 at 17:54:22.
 */
class ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Api
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Api;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pay\gateway\wechat\lib\Api::unifiedOrder
     * @todo   Implement testUnifiedOrder().
     */
    public function testUnifiedOrder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::orderQuery
     * @todo   Implement testOrderQuery().
     */
    public function testOrderQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::closeOrder
     * @todo   Implement testCloseOrder().
     */
    public function testCloseOrder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::refund
     * @todo   Implement testRefund().
     */
    public function testRefund()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::refundQuery
     * @todo   Implement testRefundQuery().
     */
    public function testRefundQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::downloadBill
     * @todo   Implement testDownloadBill().
     */
    public function testDownloadBill()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::micropay
     * @todo   Implement testMicropay().
     */
    public function testMicropay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::reverse
     * @todo   Implement testReverse().
     */
    public function testReverse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::report
     * @todo   Implement testReport().
     */
    public function testReport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::bizpayurl
     * @todo   Implement testBizpayurl().
     */
    public function testBizpayurl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::shorturl
     * @todo   Implement testShorturl().
     */
    public function testShorturl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::notify
     * @todo   Implement testNotify().
     */
    public function testNotify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::getNonceStr
     * @todo   Implement testGetNonceStr().
     */
    public function testGetNonceStr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\Api::replyNotify
     * @todo   Implement testReplyNotify().
     */
    public function testReplyNotify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
