<?php

namespace pay\gateway\wechat\lib;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-05 at 17:54:21.
 */
class BaseDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BaseData
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseData;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pay\gateway\wechat\lib\BaseData::SetSign
     * @todo   Implement testSetSign().
     */
    public function testSetSign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\BaseData::GetSign
     * @todo   Implement testGetSign().
     */
    public function testGetSign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\BaseData::IsSignSet
     * @todo   Implement testIsSignSet().
     */
    public function testIsSignSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\BaseData::ToXml
     * @todo   Implement testToXml().
     */
    public function testToXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\BaseData::FromXml
     * @todo   Implement testFromXml().
     */
    public function testFromXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\BaseData::ToUrlParams
     * @todo   Implement testToUrlParams().
     */
    public function testToUrlParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\BaseData::MakeSign
     * @todo   Implement testMakeSign().
     */
    public function testMakeSign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pay\gateway\wechat\lib\BaseData::GetValues
     * @todo   Implement testGetValues().
     */
    public function testGetValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
