<?php

namespace pay\gateway\wechat\lib;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-05 at 17:54:21.
 */
class ExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Exception
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Exception;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pay\gateway\wechat\lib\Exception::errorMessage
     * @todo   Implement testErrorMessage().
     */
    public function testErrorMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
